##### base rubocop #####
AllCops:
  Exclude:
    - local/**/*

Style/TrivialAccessors:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

##### rspec focused rubocop #####
# require: rubocop-rspec
